### ISSUE TITLE
Missing 'package' key attribute on element package at AndroidManifest.xml:10:5-54

### ISSUE THREAD

**Issue by Stinox22** [mdazharuddin1011999/UPI-Plugin-Flutter#40]
I'm facing this issue on v3.0.1

`C:\flutter-sdk\flutter\.pub-cache\hosted\pub.dartlang.org\upi_india-3.0.1\android\src\main\AndroidManifest.xml:10:5-54 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:10:5-54`

Can you tell me whats going wrong? Its urgent and I'm not able to make a build.

**Comment by azhar1038** [comment]
You need to upgrade your Android Gradle plugin 4.1+
This is due to new privacy policy of package visibility for Android 11+ [Check this for more information](https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html?m=1)

Thanks for bringing this to my attention. I will update the readme.
